//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prima.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prima.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command assembly reloaded!.
        /// </summary>
        public static string CommandAssemblyReloadSuccess {
            get {
                return ResourceManager.GetString("CommandAssemblyReloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command prefix updated!.
        /// </summary>
        public static string CommandPrefixUpdateSuccess {
            get {
                return ResourceManager.GetString("CommandPrefixUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting all entities in the User database, please wait....
        /// </summary>
        public static string DBUserCountInProgress {
            get {
                return ResourceManager.GetString("DBUserCountInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of Discord&apos;s limitations, nicknames must be 32 characters or fewer in length..
        /// </summary>
        public static string DiscordNicknameTooLongError {
            get {
                return ResourceManager.GetString("DiscordNicknameTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed!.
        /// </summary>
        public static string GenericFailure {
            get {
                return ResourceManager.GetString("GenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed!.
        /// </summary>
        public static string GenericSuccess {
            get {
                return ResourceManager.GetString("GenericSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid number!.
        /// </summary>
        public static string InvalidNumberError {
            get {
                return ResourceManager.GetString("InvalidNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid regex string!.
        /// </summary>
        public static string InvalidRegexError {
            get {
                return ResourceManager.GetString("InvalidRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The achievement has been found, and you have been given the Arsenal Master role..
        /// </summary>
        public static string LodestoneBAAchievementSuccess {
            get {
                return ResourceManager.GetString("LodestoneBAAchievementSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mount has been found, and you have been given the Cleared role..
        /// </summary>
        public static string LodestoneBAMountSuccess {
            get {
                return ResourceManager.GetString("LodestoneBAMountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord ID not found. Please ensure your Discord ID is located somewhere in your Lodestone bio..
        /// </summary>
        public static string LodestoneDiscordIdNotFoundError {
            get {
                return ResourceManager.GetString("LodestoneDiscordIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mount or achievement was not found. Please ensure your achievements and mounts are public for this operation..
        /// </summary>
        public static string LodestoneMountAchievementNotFoundError {
            get {
                return ResourceManager.GetString("LodestoneMountAchievementNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have all roles associated with this command!.
        /// </summary>
        public static string MemberAlreadyHasRoleError {
            get {
                return ResourceManager.GetString("MemberAlreadyHasRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a user mention in your command..
        /// </summary>
        public static string MentionNotProvidedError {
            get {
                return ResourceManager.GetString("MentionNotProvidedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That command must be used in a guild!.
        /// </summary>
        public static string MustBeUsedInGuildError {
            get {
                return ResourceManager.GetString("MustBeUsedInGuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified regular expression was not found in the database..
        /// </summary>
        public static string RegexNotFoundError {
            get {
                return ResourceManager.GetString("RegexNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the future, please only use the report command in my DMs. Though your report is being processed, using my DM to make the report helps maintain everyone&apos;s privacy. Thank you ^^.
        /// </summary>
        public static string ReportInGuildWarning {
            get {
                return ResourceManager.GetString("ReportInGuildWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your report. The moderators will read it as soon as they are available..
        /// </summary>
        public static string ReportThankYou {
            get {
                return ResourceManager.GetString("ReportThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved message attachments linked below. Please be aware that attempting to access deleted files may return 403 Forbidden from the CDN..
        /// </summary>
        public static string UnsavedMessageAttachmentsWarning {
            get {
                return ResourceManager.GetString("UnsavedMessageAttachmentsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user matching the query could be found..
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That user was not found in the database..
        /// </summary>
        public static string UserNotInDatabaseError {
            get {
                return ResourceManager.GetString("UserNotInDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have begun the verification process. Your **Discord account ID** is `.
        /// </summary>
        public static string VerificationProcess1 {
            get {
                return ResourceManager.GetString("VerificationProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `.
        ///Please add this somewhere in your FFXIV Lodestone account description.
        ///You can edit your account description here: https://na.finalfantasyxiv.com/lodestone/my/setting/profile/
        ///After you have put your Discord account ID in your Lodestone profile, please use.
        /// </summary>
        public static string VerificationProcess2 {
            get {
                return ResourceManager.GetString("VerificationProcess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify `Lodestone ID` to tell me your Lodestone ID **(located in your character profile URL)**..
        /// </summary>
        public static string VerificationProcess3 {
            get {
                return ResourceManager.GetString("VerificationProcess3", resourceCulture);
            }
        }
    }
}
