// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prima.Contexts;

namespace Prima.Migrations.Configuration
{
    [DbContext(typeof(ConfigurationContext))]
    [Migration("20200208092119_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Prima.Contexts.ClockConfiguration", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TzId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.ToTable("ClockData");
                });
#pragma warning restore 612, 618
        }
    }
}
