// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prima.Contexts;

namespace Prima.Migrations.TextBlacklist
{
    [DbContext(typeof(TextBlacklistContext))]
    [Migration("20200217045955_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Prima.Contexts.GuildTextBlacklistEntry", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegexString")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("RegexStrings");
                });
#pragma warning restore 612, 618
        }
    }
}
