//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prima.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prima.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock has been added! Please allow up to one minute for the clock to update..
        /// </summary>
        internal static string ClockAddSuccess {
            get {
                return ResourceManager.GetString("ClockAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock has been removed!.
        /// </summary>
        internal static string ClockRemoveSuccess {
            get {
                return ResourceManager.GetString("ClockRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command assembly reloaded!.
        /// </summary>
        internal static string CommandAssemblyReloadSuccess {
            get {
                return ResourceManager.GetString("CommandAssemblyReloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command prefix updated!.
        /// </summary>
        internal static string CommandPrefixUpdateSuccess {
            get {
                return ResourceManager.GetString("CommandPrefixUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting all entities in the User database, please wait....
        /// </summary>
        internal static string DBUserCountInProgress {
            get {
                return ResourceManager.GetString("DBUserCountInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of Discord&apos;s limitations, nicknames must be 32 characters or fewer in length..
        /// </summary>
        internal static string DiscordNicknameTooLongError {
            get {
                return ResourceManager.GetString("DiscordNicknameTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed!.
        /// </summary>
        internal static string GenericFailure {
            get {
                return ResourceManager.GetString("GenericFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed!.
        /// </summary>
        internal static string GenericSuccess {
            get {
                return ResourceManager.GetString("GenericSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Preset provided is not compatible with the operation requested..
        /// </summary>
        internal static string IncompatiblePresetError {
            get {
                return ResourceManager.GetString("IncompatiblePresetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid number!.
        /// </summary>
        internal static string InvalidNumberError {
            get {
                return ResourceManager.GetString("InvalidNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid regex string!.
        /// </summary>
        internal static string InvalidRegexError {
            get {
                return ResourceManager.GetString("InvalidRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The achievement has been found, and you have been given the Arsenal Master role..
        /// </summary>
        internal static string LodestoneBAAchievementSuccess {
            get {
                return ResourceManager.GetString("LodestoneBAAchievementSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mount has been found, and you have been given the Cleared role..
        /// </summary>
        internal static string LodestoneBAMountSuccess {
            get {
                return ResourceManager.GetString("LodestoneBAMountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord ID not found. Please ensure your Discord ID is located somewhere in your Lodestone bio..
        /// </summary>
        internal static string LodestoneDiscordIdNotFoundError {
            get {
                return ResourceManager.GetString("LodestoneDiscordIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mount or achievement was not found. Please ensure your achievements and mounts are public for this operation..
        /// </summary>
        internal static string LodestoneMountAchievementNotFoundError {
            get {
                return ResourceManager.GetString("LodestoneMountAchievementNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have all roles associated with this command!.
        /// </summary>
        internal static string MemberAlreadyHasRoleError {
            get {
                return ResourceManager.GetString("MemberAlreadyHasRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a user mention in your command..
        /// </summary>
        internal static string MentionNotProvidedError {
            get {
                return ResourceManager.GetString("MentionNotProvidedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That command must be used in a guild!.
        /// </summary>
        internal static string MustBeUsedInGuildError {
            get {
                return ResourceManager.GetString("MustBeUsedInGuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That argument must reference a voice channel, not a text channel!.
        /// </summary>
        internal static string MustBeUsedOnVoiceChannelError {
            get {
                return ResourceManager.GetString("MustBeUsedOnVoiceChannelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid timezone ID!.
        /// </summary>
        internal static string NotATimezoneIdError {
            get {
                return ResourceManager.GetString("NotATimezoneIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified regular expression was not found in the database..
        /// </summary>
        internal static string RegexNotFoundError {
            get {
                return ResourceManager.GetString("RegexNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the future, please only use the report command in my DMs. Though your report is being processed, using my DM to make the report helps maintain everyone&apos;s privacy. Thank you ^^.
        /// </summary>
        internal static string ReportInGuildWarning {
            get {
                return ResourceManager.GetString("ReportInGuildWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your report. The moderators will read it as soon as they are available..
        /// </summary>
        internal static string ReportThankYou {
            get {
                return ResourceManager.GetString("ReportThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Undefined enables all commands, without enabling the corresponding services.\nThis configuration is prohibited..
        /// </summary>
        internal static string UndefinedPresetError {
            get {
                return ResourceManager.GetString("UndefinedPresetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved message attachments linked below. Please be aware that attempting to access deleted files may return 403 Forbidden from the CDN..
        /// </summary>
        internal static string UnsavedMessageAttachmentsWarning {
            get {
                return ResourceManager.GetString("UnsavedMessageAttachmentsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user matching the query could be found..
        /// </summary>
        internal static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That user was not found in the database..
        /// </summary>
        internal static string UserNotInDatabaseError {
            get {
                return ResourceManager.GetString("UserNotInDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=Configuration.db.
        /// </summary>
        internal static string UWPConfigConnectionString {
            get {
                return ResourceManager.GetString("UWPConfigConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=DiscordXIVUsers.db.
        /// </summary>
        internal static string UWPDXIVConnectionString {
            get {
                return ResourceManager.GetString("UWPDXIVConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=Log.db.
        /// </summary>
        internal static string UWPLogConnectionString {
            get {
                return ResourceManager.GetString("UWPLogConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=TextBlacklist.db.
        /// </summary>
        internal static string UWPTextBlacklistConnectionString {
            get {
                return ResourceManager.GetString("UWPTextBlacklistConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have begun the verification process. Your **Discord account ID** is `.
        /// </summary>
        internal static string VerificationProcess1 {
            get {
                return ResourceManager.GetString("VerificationProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `.
        ///Please add this somewhere in your FFXIV Lodestone account description.
        ///You can edit your account description here: https://na.finalfantasyxiv.com/lodestone/my/setting/profile/
        ///After you have put your Discord account ID in your Lodestone profile, please use.
        /// </summary>
        internal static string VerificationProcess2 {
            get {
                return ResourceManager.GetString("VerificationProcess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify `Lodestone ID` to tell me your Lodestone ID **(located in your character profile URL)**..
        /// </summary>
        internal static string VerificationProcess3 {
            get {
                return ResourceManager.GetString("VerificationProcess3", resourceCulture);
            }
        }
    }
}
